### ISSUE TITLE
[FEAT] Allow undetermined ID values in admin_objects_ids

### ISSUE THREAD

**Issue by mloskot** [claranet/terraform-azurerm-keyvault#2]
### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'm trying to assign application (or service principal) an RBAC role to key vault created with this module:

```hcl
resource "azuread_application" "example" {
  #...snip...
}
```

```hcl
module "keyvault" {
  source  = "claranet/keyvault/azurerm"
  version = "7.5.0"

  #...snip...

  admin_objects_ids = [
    data.azurerm_client_config.current.object_id,
    azuread_application.example.object_id           # <--- troublemaker
  ]
```

but `terraform plan` complains

```
│ Error: Invalid for_each argument
│
│   on .terraform/modules/keyvault/r-rbac.tf line 2, in resource "azurerm_role_assignment" "rbac_keyvault_administrator":
│    2:   for_each = toset(var.rbac_authorization_enabled && !var.managed_hardware_security_module_enabled ? var.admin_objects_ids : [])
│     ├────────────────
│     │ var.admin_objects_ids is list of string with 2 elements
│     │ var.managed_hardware_security_module_enabled is false
│     │ var.rbac_authorization_enabled is true
│
│ The "for_each" set includes values derived from resource attributes that cannot be determined until apply, and so Terraform cannot determine the full set of keys that will identify the instances of this resource.
│
│ When working with unknown values in for_each, it's better to use a map value where the keys are defined statically in your configuration and where only the values contain apply-time results.
│
│ Alternatively, you could use the -target planning option to first apply only the resources that the for_each value depends on, and then apply a second time to fully converge.
```

If I remove the `azuread_application.example.object_id` from the `admin_objects_ids` list, then obviously the error is gone.

### New or Affected Resource(s)/Data Source(s)

azurerm_role_assignment

**Comment by BzSpi** [comment]
Hello @mloskot 

Thank you for opening this issue.

This issue is due to a Terraform limitation and cannot be fixed unless refactoring the module with a breaking change (ie. having a map with fixed key).

This refactoring is currently not planned.

**Comment by mloskot** [comment]
@BzSpi I guess - I'm still a Terraform learner - rewriting the list into a map with random keys internally by the module is not an option.

I think it would be helpful if this description captures that limitation

https://github.com/claranet/terraform-azurerm-keyvault/blob/7279907929f93599f916b5348556037052caa3a2/variables.tf#L61-L62

**Comment by Shr3ps** [comment]
This behavior is internal to Terraform, I'm not sure it needs to be documented in the variable description (it may change with next versions or with OpenTofu)

**Comment by mloskot** [comment]
@Shr3ps 
> This behavior is internal to Terraform (...)

Right, makes sense. Thanks!

**Comment by Shr3ps** [comment]
But anyway, thanks for the issue, like @BzSpi said, will try to refactor the module to avoid this in the next "major" change (unplanned for now).
